#!/bin/bash
# Production automated-test harness: loads the remapped mod jar via a real fabric dedicated server
# (bypassing the loom dev classpath loading pitfall), runs /minecraftai verify <feature> headlessly, and captures PASS/FAIL.
# Dependency: run-prod/ must already be generated by fabric-installer (fabric-server-launch.jar + server.jar).
# Usage: bash scripts/prod_test.sh [feature] [maxwait_seconds]
set -u
cd "$(dirname "$0")/.." || exit 1
PROD=run-prod
LOG=/tmp/mc_prodtest.log
FIFO=/tmp/mc_prodtest.fifo
FEATURE="${1:-food}"
MAXWAIT="${2:-600}"
: > "$LOG"

# 1) build remapped (intermediary) mod jar -- includes the latest code
echo "[prod] building minecraftai jar ..."
./gradlew --no-daemon build -x test >/dev/null 2>&1 || { echo "[prod] BUILD FAILED"; exit 1; }
MINECRAFTAI_JAR=$(ls build/libs/*.jar | grep -viE "sources|dev" | head -1)

# 2) install mods: minecraftai + fabric-api (both use the intermediary production jar)
mkdir -p "$PROD/mods"
rm -f "$PROD"/mods/*.jar
cp "$MINECRAFTAI_JAR" "$PROD/mods/minecraftai.jar"
# fabric-api uses the official maven production (intermediary) umbrella jar -- a find over the gradle cache easily picks a submodule jar instead
# (whose mod id isn't fabric-api), which leaves minecraftai missing a dependency. Cache it under run-prod to avoid re-downloading every run.
FABRIC_API_URL="https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/0.114.1+1.21.3/fabric-api-0.114.1+1.21.3.jar"
if [ ! -s "$PROD/fabric-api-cache.jar" ]; then
  echo "[prod] downloading fabric-api ..."
  curl -sL --max-time 90 -o "$PROD/fabric-api-cache.jar" "$FABRIC_API_URL"
fi
cp "$PROD/fabric-api-cache.jar" "$PROD/mods/fabric-api.jar"
echo "eula=true" > "$PROD/eula.txt"
rm -f "$PROD/world/minecraftai/bots.json" 2>/dev/null   # clear leftover bot
echo "[prod] mods: $(ls "$PROD/mods/")"

# 3) start the real server (headless), inject console commands via FIFO
rm -f "$FIFO"; mkfifo "$FIFO"
sleep 100000 > "$FIFO" & HOLDER=$!
( cd "$PROD" && exec java -Xmx2G -jar fabric-server-launch.jar nogui ) < "$FIFO" >> "$LOG" 2>&1 & SRV=$!
echo "[prod] server pid=$SRV feature=$FEATURE"

READY=0
for i in $(seq 1 480); do
  grep -q 'Done (' "$LOG" 2>/dev/null && { READY=1; echo "[prod] READY at ${i}s"; break; }
  kill -0 "$SRV" 2>/dev/null || { echo "[prod] SERVER DIED EARLY"; tail -25 "$LOG"; break; }
  sleep 1
done

if [ "$READY" = 1 ]; then
  sleep 2
  echo "minecraftai spawn TestBob assistant" > "$FIFO"; sleep 5
  echo "minecraftai verify $FEATURE" > "$FIFO"
  echo "[prod] verify '$FEATURE' dispatched, waiting up to ${MAXWAIT}s ..."
  for i in $(seq 1 "$((MAXWAIT/2))"); do
    grep -qE "\[MinecraftAi Verify\] summary" "$LOG" 2>/dev/null && { echo "[prod] finished ~$((i*2))s"; break; }
    grep -q "unknown feature" "$LOG" 2>/dev/null && { echo "[prod] UNKNOWN_FEATURE (jar doesn't include food?)"; break; }
    kill -0 "$SRV" 2>/dev/null || { echo "[prod] SERVER DIED MID-VERIFY"; break; }
    sleep 2
  done
fi

echo "[prod] stopping"
echo "stop" > "$FIFO"; sleep 10
kill "$SRV" 2>/dev/null; kill "$HOLDER" 2>/dev/null; rm -f "$FIFO"
echo "================= PROD TEST RESULT ($FEATURE) ================="
grep -E "\[MinecraftAi Verify\] (summary|$FEATURE )|unknown feature" "$LOG" 2>/dev/null | tail -3
echo "==============================================================="
